# Generated by Django 3.2.3 on 2021-06-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPiezas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pieza',
            old_name='paciente',
            new_name='residente',
        ),
    ]
