# Generated by Django 3.2.3 on 2021-06-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPiezas', '0002_rename_paciente_pieza_residente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
