# Generated by Django 3.2.3 on 2021-06-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPiezas', '0003_pieza_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
